name: Unit Test

on:
  workflow_call:

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.12.0

      - name: Install dependencies
        run: yarn install

      - name: Run audit
        run: yarn npm audit

      - name: Run typecheck
        run: yarn typecheck

      - name: Run lint
        run: yarn lint

      - name: Run build
        run: yarn build-lib

      - name: Run unit tests
        run: yarn unittest
